setalarmservice:
  name: Set Alarm
  description: Sets an Alarm on the Doppler
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler to set alarm
      required: true
      advanced: false
      selector:
        device:
          integration: sandman_doppler
    alarm_id:
      name: Alarm ID
      description: ID of the alarm to be set
      required: true
      advanced: false
      selector:
        number:
          min: 1
          max: 255
          mode: box
    alarm_name:
      name: Alarm Name
      description: Name of the Alarm
      required: true
      advanced: false
      selector:
        text:          
    alarm_time:
      name: Alarm Time
      description: The time of the alarm to set
      required: true
      advanced: false
      selector:
        time:
    repeat:
      name: Repeat Days
      description: Alarm Repeats on these days
      required: false
      advanced: false
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: Mo
            - label: Tuesday
              value: Tu
            - label: Wednesday
              value: We
            - label: Thursday
              value: Th
            - label: Friday
              value: Fr
            - label: Saturday
              value: Sa
            - label: Sunday
              value: Su
    color:
      name: Alarm Color
      desciption: Color of the Alarm on the clock
      required: true
      advanced: false
      selector:
        color_rgb:
    volume:
      name: Alarm Volume
      description: Volume for alarm separate from master volume
      required: true
      advanced: true
      selector:
        number:
          min: 0
          max: 100
          mode: slider
    status:
      name: Alarm Status
      description: Whether alarm is set or unset
      required: true
      advanced: false
      selector:
        boolean:
    sound:
      name: Alarm Sound
      description: mp3 file to play for alarm
      required: true
      advanced: false
      selector:
        select:
          options:
            - '1980.mp3'
            - 'Alarming.mp3'
            - 'Classic.mp3'
            - 'Dance.mp3'
            - 'Dialup.mp3'
            - 'Gentle.mp3'
            - 'Harp.mp3'
            - 'Jazz.mp3'
            - 'Jungle.mp3'
            - 'Playful.mp3'
            - 'Purite.mp3'
            - 'Rainforest.mp3'
            - 'Ripples.mp3'
            - 'Rooster.mp3'
            - 'Sandman.mp3'
            - 'Stream.mp3'
            - 'Sub.mp3'
            - 'Trek.mp3'
            - 'Violin.mp3'
            - 'Waves.mp3'

deletealarmservice:
  name: Delete Alarm
  description: Deletes the selected Alarm
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler to set alarm
      required: true
      advanced: false
      selector:
        device:
          integration: sandman_doppler
    alarm_id:
      name: Alarm ID
      description: ID of the alarm to be set
      required: true
      advanced: false
      selector:
        number:
          min: 1
          max: 255
          mode: box
displaytextmainservice:
  name: Main Display Text
  description: Display Text on Main Display
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler whose display to write to
      required: true
      advanced: false
      selector:
        device:
          integration: sandman_doppler
    display_text:
      name: Text to Display
      description: Text to Display
      required: true
      advanced: false
      selector:
        text:
          type: text
    display_duration:
      name: Display Duration
      description: Length of time text is displayed
      required: true
      advanced: false
      selector:
        number:
          min: 0
          max: 8675309
          unit_of_measurement: seconds
          mode: box
    display_speed:
      name: Display Speed
      description: How fast the text scrolls
      required: true
      advanced: false
      selector:
        number:
          min: 0
          max: 10000
          mode: box
    display_color:
      name: Display Color
      description: Color of Displayed Text
      required: true
      advanced: false
      selector:
        color_rgb:

displaynumminiservice:
  name: Mini Display Number
  description: Display Number on Mini Display
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler whose display to write to
      required: true
      advanced: false
      selector:
        device:
          integration: sandman_doppler
    display_number:
      name: Number to Display
      description: Number to Display on Mini Display
      required: true
      advanced: false
      selector:
        number:
          min: -199
          max: 199
          mode: box
    display_duration:
      name: Display Duration
      description: Length of time number is displayed on mini dispaly
      required: true
      advanced: false
      selector:
        number:
          min: 0
          max: 8675309
          unit_of_measurement: seconds
          mode: box          
    display_color:
      name: Display Color
      description: Color of Displayed Number
      required: true
      advanced: false
      selector:
        color_rgb:
setlightbarcolorservice:
  name: Lightbar color
  description: Sets lightbar to a single color and cycles colors if multiple colors are selected
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler whose display to write to
      required: true
      advanced: false
      selector:
        device:
          integration: sandman_doppler
    lightbar_color1:
      name: Color 1
      description: First color of lightbar
      required: true
      advanced: false
      selector:
        color_rgb:
    lightbar_color2:
      name: Color 2
      description: Second color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color3:
      name: Color 3
      description: Third color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color4:
      name: Color 4
      description: Fourth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color5:
      name: Color 5
      description: Fifth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color6:
      name: Color 6
      description: Sixth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color7:
      name: Color 7
      description: Seventh color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color8:
      name: Color 8
      description: Eighth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color9:
      name: Color 9
      description: Ninth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color10:
      name: Color 10
      description: Tenth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color11:
      name: Color 11
      description: Eleventh color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_color12:
      name: Color 12
      description: Twelveth color of lightbar
      required: false
      advanced: false
      selector:
        color_rgb:
    lightbar_duration:
      name: Duration
      description: Duration of lightbar effect
      required: true
      advanced: false
      selector:
        number:
          min: 0
          max: 8675309
          mode: box
    lightbar_speed:
      name: Speed
      description: Speed of lightbar effect
      required: true
      advanced: false
      selector:
        number:
          min: 0
          max: 255
          mode: box
    lightbar_sparkle:
      name: Sparkle
      description: Makes sparkles in the effect
      required: false
      advanced: false
      selector:
        select:
          options:
            - low
            - medium
            - high
    lightbar_rainbow:
      name: Rainbow
      description: Replaces specified palette with rainbow effect
      required: false
      advanced: false
      selector:
        boolean:
