setalarmservice:
  name: Set Alarm
  description: Sets an Alarm on the Doppler
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler to set alarm
      selector:
        device:
          integration: sandman_doppler
    alarm_id:
      name: Alarm ID
      description: ID of the alarm to be set
      required: true
      advanced: false
      selector:
        number:
          min: 1
          max: 255
          mode: box
    alarm_name:
      name: Alarm Name
      description: Name of the Alarm
      required: true
      advanced: false
      selector:
        text:          
    alarm_time:
      name: Alarm Time
      description: The time of the alarm to set
      required: true
      advanced: false
      selector:
        time:
    repeat:
      name: Repeat Days
      description: Alarm goes off on these days
      required: true
      advanced: false
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: Mo
            - label: Tuesday
              value: Tu
            - label: Wednesday
              value: We
            - label: Thursday
              value: Th
            - label: Friday
              value: Fr
            - label: Saturday
              value: Sa
            - label: Sunday
              value: Su
    color:
      name: Alarm Color
      desciption: Color of the Alarm on the clock
      required: true
      advanced: false
      selector:
        color_rgb:
    volume:
      name: Alarm Volume
      description: Volume for alarm separate from master volume
      required: true
      advanced: true
      selector:
        number:
          min: 0
          max: 100
          mode: slider
    status:
      name: Alarm Status
      description: Whether alarm is set or unset
      required: true
      advanced: false
      selector:
        boolean:
    sound:
      name: Alarm Sound
      description: mp3 file to play for alarm
      required: true
      advanced: false
      selector:
        select:
          options:
            - '1980.mp3'
            - 'Alarming.mp3'
            - 'Classic.mp3'
            - 'Dance.mp3'
            - 'Dialup.mp3'
            - 'Gentle.mp3'
            - 'Harp.mp3'
            - 'Jazz.mp3'
            - 'Jungle.mp3'
            - 'Playful.mp3'
            - 'Purite.mp3'
            - 'Rainforest.mp3'
            - 'Ripples.mp3'
            - 'Rooster.mp3'
            - 'Sandman.mp3'
            - 'Stream.mp3'
            - 'Sub.mp3'
            - 'Trek.mp3'
            - 'Violin.mp3'
            - 'Waves.mp3'

deletealarmservice:
  name: Delete Alarm
  description: Deletes the selected Alarm
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler to set alarm
      selector:
        device:
          integration: sandman_doppler
    alarm_id:
      name: Alarm ID
      description: ID of the alarm to be set
      required: true
      advanced: false
      selector:
        number:
          min: 1
          max: 255
          mode: box
