testservice:
  name: Test Service
  description: Test
  target:
    entity:
      integration: sandman_doppler
  fields:
    test_field:
      name: Testfield
      description: Test
      required: true
      advanced: false
      example: "low"
      default: "high"
      selector:
        time:
timezoneservice:
  name: Timezone
  description: Sets Timezone
  target:
    entity:
      integration: sandman_doppler
  fields:
    timezone:
      name: Timezone
      description: Timezone to set
      required: true
      advanced: false
      example: "America/Los_Angeles"
      default: "UTC"
      selector:
        text:

