setalarmservice:
  name: Set Alarm
  description: Sets an Alarm on the Doppler
  fields:
    doppler_device_id:
      name: Doppler ID
      description: ID of doppler to set alarm
      selector:
        device:
          integration: sandman_doppler
    alarm_time:
      name: Alarm Time
      description: The time of the alarm to set
      required: true
      advanced: false
      default: true
      selector:
        time:
    sunday:
      name: Sunday
      description: Is alarm active on Sunday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    monday:
      name: Monday
      description: Is alarm active on Monday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    tuesday:
      name: Tuesday
      description: Is alarm active on Tuesday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    wednesday:
      name: Wednesday
      description: Is alarm active on Wednesday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    thursday:
      name: Thursday
      description: Is alarm active on Thursday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    friday:
      name: Friday 
      description: Is alarm active on Friday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
    saturday:
      name: Saturday
      description: Is alarm active on Saturday
      required: true
      advanced: false
      default: true
      selector:
        boolean:
