setalarmservice:
  name: Set Alarm
  description: Sets an Alarm on the Doppler
  target:
    entity:
      integration: sandman_doppler
  fields:
    alarm_time:
      name: Alarm Time
      description: The time of the alarm to set
      required: true
      advanced: false
      selector:
        time:
